In [1]:
import numpy as np

In [2]:
beninListem = [20,30,40]
print(type(beninListem))

<class 'list'>


In [3]:
benimListemNumpy = np.array(beninListem)
print(type(benimListemNumpy))
print(benimListemNumpy)

<class 'numpy.ndarray'>
[20 30 40]


In [9]:
matrixListesi = [[10,20,30],[20,30,40],[40,50,60]]
print(matrixListesi)

matrixListesiNumpy = np.array(matrixListesi)
print(type(matrixListesiNumpy))
print(matrixListesiNumpy)

[[10, 20, 30], [20, 30, 40], [40, 50, 60]]
<class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]
 [40 50 60]]


In [18]:
print(matrixListesi[0])
np.array(matrixListesi)

[10, 20, 30]


array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

Np.Arrange : 


In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,2) #0 = begin number, 10=end number,  2=step number

array([0, 2, 4, 6, 8])

In [31]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((4,4),dtype= int)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])