In [38]:
import numpy as np

In [39]:
beninListem = [20,30,40]
print(type(beninListem))

<class 'list'>


In [40]:
benimListemNumpy = np.array(beninListem)
print(type(benimListemNumpy))
print(benimListemNumpy)

<class 'numpy.ndarray'>
[20 30 40]


In [41]:
matrixListesi = [[10,20,30],[20,30,40],[40,50,60]]
print(matrixListesi)

matrixListesiNumpy = np.array(matrixListesi)
print(type(matrixListesiNumpy))
print(matrixListesiNumpy)

[[10, 20, 30], [20, 30, 40], [40, 50, 60]]
<class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]
 [40 50 60]]


In [42]:
print(matrixListesi[0])
np.array(matrixListesi)

[10, 20, 30]


array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

Np.Arrange : 


In [43]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0,10,2) #0 = begin number, 10=end number,  2=step number

array([0, 2, 4, 6, 8])

In [45]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((4,4),dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
np.linspace(0,100,9) # 0 ile yüz arasında 5 tane eşit mesafede liste oluştur

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [48]:
np.linspace(0,100,9,endpoint=False)

array([ 0.        , 11.11111111, 22.22222222, 33.33333333, 44.44444444,
       55.55555556, 66.66666667, 77.77777778, 88.88888889])

In [49]:
np.eye(5) # identity matrix oluşturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.random.randn(10) # 10 adet elamana ait rasgele dizi üretir
np.random.randn(3,3) # 3,3 lük bir rastgele matrix oluşturur 

array([[-0.05433944, -1.61512865, -1.3063505 ],
       [-0.49514597, -0.03496166, -0.3501773 ],
       [-1.14472848,  0.56824686,  1.03027296]])

In [51]:
npResim = np.random.randint(0,256,(3,256,256))
npResim
# np.save(npResim,)

array([[[110, 189,  19, ..., 146,  43, 178],
        [ 14,  97,  91, ..., 140, 225, 141],
        [112,  92, 228, ..., 123, 120,  91],
        ...,
        [155,  91,  11, ..., 128, 223, 136],
        [ 91,  29, 185, ..., 159,  94, 225],
        [  0, 207,  61, ..., 248, 100, 247]],

       [[249, 119, 144, ..., 230,  23, 248],
        [ 35, 106,  11, ...,  22,  22, 225],
        [216,  83,  51, ...,  11, 224,  67],
        ...,
        [113, 204,  13, ..., 200,  24,  45],
        [115, 169, 119, ...,  54,  79, 204],
        [ 81, 149, 115, ..., 229, 213,  59]],

       [[175, 200, 247, ..., 229, 175,  57],
        [ 81, 157,  96, ..., 174,  68, 246],
        [119, 217, 163, ..., 190, 199,  98],
        ...,
        [244,  25,  41, ..., 114, 141, 154],
        [187, 185,  65, ...,  68, 212,  10],
        [178, 245,  55, ...,  54, 237,  56]]])

#Fonksiyonlar

In [52]:
benimNumpyDizi = np.random.randn(30)
benimNumpyDizi

array([ 0.01308175, -0.23108821,  1.0885176 , -0.13164782, -0.12787967,
        0.43057832,  0.47932117,  0.16642368, -0.43175773,  0.24605071,
       -1.05523189, -0.9148219 ,  1.79603315, -0.25996519, -0.2216804 ,
       -1.00568549, -0.39164677,  0.35783569,  0.63310187, -0.25448666,
        0.11920595, -0.13552913, -1.40443383, -0.08797016,  0.18256453,
       -0.88976041,  0.89681774,  0.42718291, -2.28667327,  0.16636033])

In [53]:
benimNumpyDizi =benimNumpyDizi.reshape(5,6)
benimNumpyDizi

array([[ 0.01308175, -0.23108821,  1.0885176 , -0.13164782, -0.12787967,
         0.43057832],
       [ 0.47932117,  0.16642368, -0.43175773,  0.24605071, -1.05523189,
        -0.9148219 ],
       [ 1.79603315, -0.25996519, -0.2216804 , -1.00568549, -0.39164677,
         0.35783569],
       [ 0.63310187, -0.25448666,  0.11920595, -0.13552913, -1.40443383,
        -0.08797016],
       [ 0.18256453, -0.88976041,  0.89681774,  0.42718291, -2.28667327,
         0.16636033]])

In [54]:
print("Max Number" + str(benimNumpyDizi.max()))
benimNumpyDizi.argmax() #index of max element

Max Number1.7960331526022877


12

In [55]:
benimNumpyDizi.shape


(5, 6)

In [56]:
liste = np.arange(5,25)
liste

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [57]:
print(liste[5])
liste[5:10] = -99 #Silicing operation, 10. eleman değil, 9 da son buluyor
liste


10


array([  5,   6,   7,   8,   9, -99, -99, -99, -99, -99,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24])

In [58]:
silicingListe = liste[2:9]
silicingListe[:] = -99
silicingListe

array([-99, -99, -99, -99, -99, -99, -99])

In [59]:
liste # Listenin içi değimemiş olmamalıydı sanki ?
silicingListe = liste[2:9].copy()
silicingListe[:] = -5
silicingListe

array([-5, -5, -5, -5, -5, -5, -5])

In [60]:
liste

array([  5,   6, -99, -99, -99, -99, -99, -99, -99, -99,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24])

Matrix Indexler

In [61]:
ornekMatrix = [[2,5,6],[8,6,8],[8,3,1]]
ornekMatrix = np.array(ornekMatrix)
print(ornekMatrix)
print("2,1 Elamanı : " + str(ornekMatrix[2,1]))

[[2 5 6]
 [8 6 8]
 [8 3 1]]
2,1 Elamanı : 3


In [62]:
print(ornekMatrix[1:])
print(ornekMatrix[1:,2])


[[8 6 8]
 [8 3 1]]
[8 1]


In [63]:
yeniListe = np.random.randint(0,30,30)
yeniListe = yeniListe.reshape(5,6)
yeniListe

array([[20, 16, 29,  1,  4, 20],
       [12, 24,  7, 23, 13, 11],
       [ 0,  4, 18,  7,  6, 26],
       [20, 28,  1, 14, 16, 23],
       [14,  0,  3, 25, 21, 22]])

In [64]:
yeniListe[[2,4,0]]

array([[ 0,  4, 18,  7,  6, 26],
       [14,  0,  3, 25, 21, 22],
       [20, 16, 29,  1,  4, 20]])

In [67]:
filtrelenmis =yeniListe > 20

In [68]:
yeniListe[filtrelenmis]
# yeniListe[yeniListe>20]

array([29, 24, 23, 26, 28, 23, 25, 21, 22])

In [75]:
powererListe =yeniListe*yeniListe
powererListe

array([[400, 256, 841,   1,  16, 400],
       [144, 576,  49, 529, 169, 121],
       [  0,  16, 324,  49,  36, 676],
       [400, 784,   1, 196, 256, 529],
       [196,   0,   9, 625, 441, 484]])

In [76]:
np.sqrt(powererListe) == yeniListe

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])